### ISSUE TITLE
OSX Zip File does not extract properly

### ISSUE THREAD

**Issue by jasperf** [Temptin/SkypeExport#10]
Seems that the SkypeExport-1.3.0_osx_intel_32_64.zip does not unzip properly. I get a SkypeExport-1.3.0_osx_intel_32_64.zip.cpgz instead of the files/folder. Perhaps the zipping did not go well?

**Comment by SungMatt** [comment]
Same here. I was also unable to find the .sh file for compilation, so I'm a bit stuck at the moment.

**Comment by SungMatt** [comment]
Ignore the above comment about the .sh file. For those looking for it,  it is in `src/SkypeExport/_gccbuild/macosx/build_macosx.sh`

**Comment by mmontag** [comment]
You can get around the problem by running `unzip path-to-SkypeExport.zip` in a terminal.

**Comment by Temptin** [comment]
Hmm, you're right... maybe there's a bug in Apple's Archive Utility. If I extract with that, I get a ".cpgz" file too. If I extract with BetterZip or unzip in the terminal, I get the proper file...

I am going to release v1.4.0 in a moment, and I'll make sure that next zip works with Apple's own utility.

Really have no idea why it didn't work there. Zip is universal.

Edit: Next update is finished and being prepared for release, so I'll close this issue.

Edit2: Yep... had to use Apple's Archive Utility to create the archive. Otherwise I kept getting cpgz files upon extraction with it. It only accepts its own zip files. This isn't the first time their utility does weird things.

Strange that it took so long for people to report this since the OS X zip has had 1400 downloads. Maybe third party extraction utilities are very common. I certainly don't like Apple's built-in one, since it has issues like this one. ;-)

**Comment by Temptin** [comment]
Mystery solved. From BetterZip 3.04 (my compressor) changes:

"Since the Deflate64 compression method which was used for zip archives compressed with the “best, but slower” setting is not supported by Apple’s Archive Utility, I have gone back to using the normal Deflate method. You can still get this, by adding -mm=Deflate64 as an “additional parameter”."
