### ISSUE TITLE
Any way to get older history than what's in my Skype database?

### ISSUE THREAD

**Issue by dgrad** [Temptin/SkypeExport#13]
Running the tool I don't get any history going back before July 26 2013. Is there any way to get history older than that?

**Comment by Temptin** [comment]
Hi dgrad!

SkypeExport scans your database for every person you've ever talked to and what conversation IDs they've been in, using an extremely thorough scan to find all conversations (it looks in multiple fields of all messages to find every conversation where the chat partner has been involved). It then exports _all_ messages in the database with those conversation IDs, regardless of how old the messages are, which means it finds _every_ message that's in the database for that person.

This thorough scanning is why SkypeExport can export messages that the official Skype can't even see anymore.

Since you've got a cutoff date of July 26, 2013 in your exported history, it means that's the oldest message you've got in the database. If you've deleted your Skype database a few years ago and started fresh, then you'll be missing the history before that. There is no way to get that lost history back, since Microsoft only keeps history for 30 days in the past in the cloud, so you couldn't download it from anywhere unfortunately.

I am sure you don't have older messages in your database, because all messages _must_ always have a conversation ID (conv_id) associated with them (otherwise they'd be orphaned; thankfully Skype never orphans messages), which means that we _will_ export _all_ messages for every conversation for every user.

If you download a SQLite viewer and look in the Messages table (if I remember the name correctly) of your main.db file, you will see your raw messages and the unix timestamps of them. You can take the oldest timestamp and go to unixtimestamp.com to check what date it corresponds to. If you've got older messages than July 2013 that aren't in the export, then that'd be the first time it happens in the 5 years that this application has been active. But I doubt it, since the code is very thorough and broad in scanning for messages so that it catches them all (it's _much_ more thorough than the official Skype client).

Closing this ticket, but you're welcome to comment on it again. Good luck! :)

**Comment by dgrad** [comment]
ah, I see. I was hoping the cloud is the source of truth for this data and has a full history. I looked at the database and Jul 26, 2013 is indeed the date of the oldest message in there. thanks for the info

**Comment by Temptin** [comment]
I am very glad the Microsoft cloud doesn't have the full history. Just imagine the privacy issues of Microsoft keeping all chats forever. They only keep it for as long as necessary to do cloud history syncing between all your devices and to comply with law enforcement.

Thanks for the follow-up message and status report. :)
