### ISSUE TITLE
group discussion export doesn't seems to work

### ISSUE THREAD

**Issue by zehunter** [Temptin/SkypeExport#18]
Hi,

i found this application that is just perfect, but it doesn't take care of group discusion, is it a bug a some feature to add ?

regards,

**Comment by sthoduka** [comment]
you mean conference calls/chats? It should work. Does it print an error or something?

**Comment by cybervitor** [comment]
After exporting all of your contacts, check out the file from one of your contacts which was on the group discussion, it should be there, after the private messages to that contact.

**Comment by zehunter** [comment]
i,

i was imagine to see group discussion in separate file.. more easy to read
old discussion like that.
i will try again to export and see if i ca see discussion group inside
contact export file

regards,

**Comment by zehunter** [comment]
Ok it seems to work as you explain to me.

thanks a lot,

regards,

**Comment by aitte2** [comment]
yep the group chats are at the end of the persons chat history file. this is because your friends _private_ chat history file has links that say something like "Joined a group conversation", and you can simply click those links to automatically scroll down to that chat. this is great, because you can read it all logically in 1 file and easily see what happened. :) this ticket can be closed.
