### ISSUE TITLE
Handle NULL "author" field corruption in Skype database

### ISSUE THREAD

**Issue by watsonbox** [Temptin/SkypeExport#4]
I just ran the new version with exactly the same arguments as the old one (which works) and got the following:

```
Skype History Exporter v1.1.0 Stable
   WEBSITE: [ https://github.com/Temptin/SkypeExport ]
  DATABASE: [ "/Users/xxx/Library/Application Support/Skype/watsonbox/main.db" ]
    OUTPUT: [ "/Users/xxx/Downloads/SkypeExport/" ]
  CONTACTS: [ "*" ]

Found 100 contacts in the database...

 * Exporting:  ()
   => "/Users/xxx/Downloads/SkypeExport/.skypelog.htm"
Error while processing Skype database: "unable to locate Conversation ID in database".
```

**Comment by Temptin** [comment]
@watsonbox Thanks for the report, I think I know what's going on already! First off; that message comes from the new skypeid -> conversation ID mapping which was required to get around the random Skype database "dialog_partner=NULL" bug.

Let's say you have a contact called "grince.farbgold". The main export function would be called with "grince.farbgold" as argument. It would then run the following code to discover the actual convo_id for your main 1on1 conversation with that user:

https://github.com/Temptin/SkypeExport/commit/956879429a079f2aecedb7ec5d4c68217184bd0a#diff-8f74996125abdb7c038604bb0975170cR293
(line 293 is highlighted)

I have a very strong suspicion about why this is happening for you: Your database contains some user who was never on your contact list, and was probably only added to a mutual conference by someone else. So you never had a chance to have a 1on chat with them. You've only talked to that user via a conference. It's an obscure edge case which explains why I didn't encounter it myself.

I need more information from you to be able to fix this.

1) Please write down the name of the skypeid that fails to export.
2) Then open your main.db in a SQLite viewer and run this query (with their name):

```
SELECT id, type FROM Conversations WHERE (identity='grince.farbgold')
```

Any results with type 2 are conferences.
I suspect that you have no type 1 (1on1 chat) with that person, which in turn makes the main program's query fail.

Lastly, 3) Double-check the database to make sure you have no 1on1 chats with that person. You could do something like:

```
SELECT * FROM Messages WHERE ((author='grince.farbgold' OR dialog_partner='grince.farbgold' OR identities LIKE '%grince.farbgold%') AND convo_id!=1000)
```

(substitute their name in all 3 places, be sure to keep the %% around the LIKE statement, and replace convo_id!=1000 with the id from the type2 conference you found in step 2. This will filter away all conference events so that you can see if you have _any_ non-conference events for that user whatsoever; if so, please give me a summary of the "type" column's numbers and convo_ids for those external events).

If it turns out it's possible to have zero 1on1 chats with a user, then I will be able to move forwards with a fix which would detect when a contact has no 1on1 chat. First I just have to be 100% sure that this is the correct move and that this is indeed the issue.

**Comment by watsonbox** [comment]
@Temptin Unfortunately I don't know the name of the Skype ID which fails to export.  You have all the info I have in the issue description.  I'll try to find another way to find out.

**Comment by Temptin** [comment]
@watsonbox Really? I thought your output was censored and that you'd manually removed their name. You mean that there's _actually_ a blank/empty name in your output and that this is what you see as the first exported person's name?

```
 * Exporting:  ()
   => "/Users/xxx/Downloads/SkypeExport/.skypelog.htm"
Error while processing Skype database: "unable to locate Conversation ID in database".
```

If so, there's corruption in your database. If you run the previous version and look through the list, do you see an empty entry there too? I suspect you would since none of the skypeid-scanning code has changed. And it should be the 1st entry in the list there too, since it's alphabetically sorted and an empty string would be the first result.

You may have found another one of Skype's "great" NULL bugs! This is the fun of finding all kinds of bugs in their messy database.

The list of all people you've ever chatted with is built using:
https://github.com/Temptin/SkypeExport/blob/master/src/SkypeExport/model/skypeparser_core.cpp#L65

Particularly, this:

```
SELECT DISTINCT author FROM Messages ORDER BY author ASC
```

If it truly finds an empty user ID, then you've got a NULL bug again. The only reason the previous version didn't complain is the earlier method used to extract messages was okay with empty names. The new one strictly tries to find the 1on1 chat before proceeding with exporting a user and would of course fail on an empty name.

I need you to run this query in your database (the command line sqlite3 built into OS X will work fine):

```
SELECT author, type, convo_id, body_xml FROM Messages WHERE (author IS NULL OR author='' OR author=' ')
```

That will check for null, empty string, and a single space, to try to figure out what is going on.

I get zero results for that with my current (pretty small, a few thousand events) Skype 7 database, and zero results with my massive (tens of thousands of events in the Messages table) Skype 4/5 database. But judging from the message you're seeing I suspect you will get results.

Could you please run the query and see what type of "author" you have (null, empty string or single space)? My guess is NULL since they'd have no reason to write an empty string. Please also paste the results of the "type", "convo_id" and "body_xml" grabbing above (censor any personal messages if they appear), as I need to know what kind of events Skype could be so stupid as to corrupt the "author" property for (it should never happen). A blank author means I _might_ have to adjust the message parsing code a bit as well, to deal with the empty author cases.

Are you comfortable with compiling? If so, change the SQL on this line:
https://github.com/Temptin/SkypeExport/blob/master/src/SkypeExport/model/skypeparser_core.cpp#L65
to:

```
SELECT DISTINCT author FROM Messages WHERE author IS NOT NULL ORDER BY author ASC
```

(PS: the reason we do this and "don't just get contacts from the Contacts table" is that it wouldn't include past deleted contacts if we did that)

That should fix it; but even if it doesn't, I'll be including that change in the next version of the code since it's a good idea to safeguard against more NULL bugs. I will also review all SQL statements to see if anything else might be screwed over by their random database corruption, and add "IS NOT NULL" wherever required.

Building on OS X is very easy now; just check the readme in the _gccbuild folder and run the ./build_macosx.sh script.

After compiling with that change, it would be interesting to find out if you _still_ encounter the error with _another_ contact due to my previous suspicion that missing 1on1 chats for brief, external conference partners can also be a problem. I will try to find time to do some separate testing of that potential issue after we've fixed this one.

**Comment by Temptin** [comment]
@watsonbox If you have some time left over, please run the tests so that I can proceed with a patch. I can't do anything until the exact cause has been nailed down. ;-)

**Comment by Temptin** [comment]
@watsonbox Since you're extremely difficult to reach (not checking your notifications on Github?), I was forced to move ahead with the most likely solution.

I've now ensured that we never grab any NULL authors, as well as reviewed all code to ensure that NULL authors (or _any_ other bugged NULL fields) will never cause any problems during parsing. This meant that the author and from_dispname scanning was slightly revised.

Next, thanks to having found the "NULL author" database bug (due to throwing that error, otherwise it would never have been found), it's now impossible to find any invalid authors, so I changed the error you've seen above. It no longer throws an error. If it fails to find a 1on1 chat, it now simply outputs a hidden HTML tag which says "". That change will come in handy when you've encountered someone in a conference (because a mutual friend added them) but never spoken to them 1on1. It will now output such people properly.

Finally, to make the update even more worthwhile, I also implemented three long-time minor feature wishes of mine: Command line switches for 12/24h time, optional use of UTC time (instead of local timestamps), as well as showing the active UTC offset in the output (such as "All times are UTC+02:00").

You can find everything on the latest Release page:

https://github.com/Temptin/SkypeExport/releases

**Comment by Temptin** [comment]
@watsonbox I would _really_ like the following quick testing from you, since you're the guy with the corrupt database:
- Download v1.2.0.
- Run an export and look at the _top_ of the list of exported names. If your author field was indeed NULL (the most likely database corruption), this change should have fixed it so that you no longer see any entry with a blank name. As part of the update, we no longer throw any error during export, so the only way to verify that everything is okay is that you _must_ look at the list of exported contacts manually to make sure it has no blank name anymore. Please confirm that you no longer see this at the top of your export results (or anywhere else in the list for that matter): " \* Exporting:  ()  => "/Users/xxx/Downloads/SkypeExport/.skypelog.htm"".
- See if you have any contacts without 1on1 chats. Do that by typing the following command and seeing if you find any such people, and if so I'd like you to inspect their .html file to see if it looks correct to you:

```
grep -Ri "There is no 1on1 chat history for this person" ./ExportedHistory
```
- Lastly, I _really_ need you to run this query in your database and give me the output (the command line sqlite3 built into OS X will work fine):

```
SELECT author, type, convo_id, body_xml FROM Messages WHERE (author IS NULL OR author='' OR author=' ')
```

That will check for null, empty string, and a single space, to try to figure out what was going on with your database. I need to know exactly what kind of message types Skype risks corrupting the "author" field for, since a NULL/empty author clearly violates their database specification. _Every_ event is supposed to have an author, otherwise it's _literally impossible_ to map the event to its author. ;-) Silly Skype with its silly bugs...

**Comment by watsonbox** [comment]
Apologies I don't have time to look at this right now as I'm busy with other things but will be sure to check it out when I have more time.

**Comment by Temptin** [comment]
@watsonbox Alright, no problem. In case you didn't see it, v1.2 is out now and probably fixes the issue, which means that the testing on your end is very easy. I look forward to hearing your results when you have time.

**Comment by Temptin** [comment]
@watsonbox I'm doing finishing touches on the new Linux version of SkypeExport and the release of version 1.3.

Could you _please_ have a look at v1.2 now to see if it solved your database issue?

**Comment by watsonbox** [comment]
@Temptin Yes it works now thanks a lot.

**Comment by Temptin** [comment]
@watsonbox I am very happy to hear back from you and that it seems the bug is fixed, since I was hoping it would be gone in time for the 1.3 release later today (which you should get by the way; it has had over 10 commits with fixes for _all_ final bugs in Skype 6+'s database format, mostly its crazy NULL corruption/"cloud history" garbage!). It is the _final_ version with Skype 6/7 fixes and the only one you will ever need.

However, before we can close this old issue, I need you to actually look at the text output of the export. When I rewrote the contact scanner to ignore NULL authors, I also removed the error message that you were seeing, so while it is _very likely_ that it's truly fixed, there's no guarantee until you follow these instructions:

Run an export and look at the _top_ of the list of exported names. If your author field was indeed a NULL bug (the most likely database corruption), this change will have fixed it so that you no longer see any entry with a blank name in the list. Please confirm that you no longer see this at the top of your export results (or anywhere else in the list for that matter): " \* Exporting:  ()  => "/Users/xxx/Downloads/SkypeExport/.skypelog.htm"".

If that's gone now, then we're done at last! :-) If it's still there, then you've got an empty string as author, and in that case I'll have to add that in as an "avoid" case too -- hopefully in time for 1.3.

**Comment by watsonbox** [comment]
Yes it's still there in the logs.

```
* Exporting:  ()
   => "./ExportedHistory/.skypelog.htm"
```

**Comment by Temptin** [comment]
@watsonbox Okay then it's an empty string, and it means we're writing an empty-named logfile (.skypelog.htm is being created above). That's not good. I am pretty sure this is a bug with the "cloud history" in Skype, as I have seen it sometimes insert empty strings instead of real values.

I'll fix it, but I need to know if it's a space or an empty string. Most likely just an empty string.

Check these 3 please and see which ones match, and please also tell me the "type" id of the matching messages (very useful, so I can see if I need to fix the parser to deal with the empty author):

```
SELECT author, type, convo_id, body_xml FROM Messages WHERE (author IS NULL)
SELECT author, type, convo_id, body_xml FROM Messages WHERE (author='')
SELECT author, type, convo_id, body_xml FROM Messages WHERE (author=' ')
```

If you can do that, I'll push a commit with the solution in time for 1.3 and then we're done :)

**Comment by watsonbox** [comment]
I get results for the second one but neither of the others.

**Comment by Temptin** [comment]
@watsonbox Perfect. And wow thanks for the quick reply!

That _confirms_ that it's the "cloud history" thing. When you chat, it stores everything on Skype's servers, and I discovered that they often corrupt a little bit of the data, making it either NULL or an empty string. I spent the whole day yesterday fixing all of those database issues.

I will push a commit any minute now with the fix, and the 1.3 release comes later tonight (need to write changelog etc, takes time).

Just curious, what's the message type that has the empty author?

```
SELECT type FROM Messages WHERE (author='')
```

**Comment by watsonbox** [comment]
Type 30.

**Comment by Temptin** [comment]
Ahh... type:30 = "call start". I guess it's just random cloud corruption and not specifically targeted at that event. Before releasing 1.3, I'll take another run through the source to make sure we never use "author" in a way that would collapse on an empty string. I don't think we do, but it needs to be checked. Skype's damn "cloud history" bs has made the database a lot worse to parse, but I've covered _all_ encountered corruption issues now (there were lots more than just this one). The funny thing is that even the real Skype itself goes crazy on certain corrupt cloud data and bugs the GUI. That's a sign of poor design by the morons at Microsoft. ;-) Another funny detail about their poor design: Every time you send a message to someone, it sends a https request to a Microsoft server and passes along like 30 cookies (that's a LOT of extra bytes), when they could have survived with just 1 or 2 authentication cookies. And their whole database is a buggy Frankenstein of old and new technology now. They're really clueless... Ever since they purchased Skype they've been screwing up the code and trying to hack their own features into it. But despite all their craziness, I think we have all their bugs covered now with 1.3.

Thank you again for doing the necessary investigation. The commit which fixes this issue is now up (don't mind that it says "2 hours ago"; I amended the fix to that commit):
https://github.com/Temptin/SkypeExport/commit/8c28b01cd6ed6fdb92f5ad1e17bdd9a7856047c1

I'll be releasing 1.3 later tonight, and I'll be sure to ping you here one _last_ time when it's up, so you don't have to keep checking the release page. Enjoy, and thanks again for all your contributions!

**Comment by Temptin** [comment]
@watsonbox Alright, it's out. Version 1.3 is _the definitive_ version of SkypeExport for all your future needs: https://github.com/Temptin/SkypeExport/releases

It has removed all reliance on the various database fields that the cloud sometimes corrupts, and will work for many years to come now. There will be no more releases, since all of the Skype 6/7 quirks are now fully supported. Enjoy and have fun!
