### ISSUE TITLE
Issue with conversations that contain ":"

### ISSUE THREAD

**Issue by Himeko7** [Temptin/SkypeExport#7]
Since filenames don't allow the character ":", the exporter fails to create the corresponding conversation file for those that have this char in their name.

**Comment by Temptin** [comment]
Hi Himeko.

How is that even possible? Skype IDs only allow a-z, 0-9 and a few things like . and underscore. The files that we export are named after the person's Skype ID. So there should be no colons anywhere.

The Skype ID scanner looks for all names that do not contain # or $ or @, so that it avoids all "internal" Skype data (this highlighted comment shows examples of such internal names):
https://github.com/Temptin/SkypeExport/blob/master/src/SkypeExport/model/skypeparser_core.cpp#L67

The only thing I can think of is that you're encountering some kind of different, internal name containing a colon.

Please provide more information; I'd like to see an export-log with the broken entry. You can censor all names of all other participants.

**Comment by Himeko7** [comment]
Here you go

[censored]

It doesn't give any error whatsoever, but the file obviously doesn't exist.

Maybe it's a very old account and they used to allow this before? Please edit my post after you see it and remove the links, for obvious reasons :)

Btw I can make a GUI to use the command-line tool if you would like, I develop in Delphi.

Thank you for your awesome tool :)

**Comment by Temptin** [comment]
Thanks for the extra info! It turns out it's a Microsoft feature... They've auto-created "fake" Skype accounts for all of their Windows Live IDs. So if your Microsoft ID was "cooldude123", it would create a Skype account called "live:cooldude123". The colon is still an illegal character and the only way to get it is via this auto-creation.

We need to sanitize the output filename; but we can't just convert it to an underscore, since it could collide with real Skype IDs then... Another method may be to do what Skype itself does... If you check your friend's computer, you'll see it's actually saved as "%appdata%\Skype\live#3axxxx"... So maybe we should export all "live:" users as "live#3acooldude123.html" to match Microsoft's stupidity... but that's so ugly and to the users it would look like a SkypeExport bug.

Maybe replace the colon with a legal character that's still special and won't appear in any Skype IDs? Here are some ideas:
- live#cooldude123.html
- live$cooldude123.html

The # has the downside of looking like a HTML anchor if you ever upload the files anywhere (it would read "live" and try to jump to #cooldude123.html...

So it looks like the winner is "live$cooldude123.html". Unless you have a better idea perhaps?

Thanks for the offer about a GUI wrapper, but that's not necessary. The command is so simple that a wrapper doesn't help much, and a Delphi one would only work on Windows. If there's ever a GUI it should be a native C++ GUI which can display a list of found users and the ability to choose which ones to export, etc. It'd actually be really easy to make by just replacing the code in main.cpp with a GUI version instead.

I considered writing one in Qt5 (a very nice, cross-platform GUI framework), but the only reason there's no GUI for SkypeExport is that Qt apps take up like 50 Mb in .dll files on Windows, and ~20-30 Mb on Mac OS. :-/ The only solution that keeps a small filesize would be to make totally native GUIs using Xcode on Mac and Visual Studio on Windows, and I don't have time for that.

**Comment by Himeko7** [comment]
Oh! that makes sense, now that I think about it, this guy was using MSN before and I remember him saying he would use that account with skype after they'd shut it down. And yeah.. skype sucks at the moment, ever since m$ acquired it, it's just going downhill, both on pc and phone, but sadly call quality is still the best among all these type of apps :/

As for what to do.. not sure, maybe check whether the file already exists, and add a (2) if so?

I went ahead and made a little GUI, on startup it finds all the usernames or gives the option to supply the folder (maybe running as portable), then you can pick the username and time format and go, then then results go in the little memo box, no need to launch a DOS window or anything.

http://i.imgur.com/tLPVC3P.png

sorry for the horrible editing skills :)

lil code:

unit Unit1;

interface

uses
  Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants, System.Classes, Vcl.Graphics,
  Vcl.Controls, Vcl.Forms, Vcl.Dialogs, Vcl.Buttons, PngSpeedButton,
  Vcl.StdCtrls,

  MyStrStuff, MySysStuff;

type
  TForm1 = class(TForm)
    Edit1: TEdit;
    PngSpeedButton1: TPngSpeedButton;
    ComboBox1: TComboBox;
    Label1: TLabel;
    ComboBox2: TComboBox;
    Label2: TLabel;
    Button1: TButton;
    Memo1: TMemo;
    Button2: TButton;
    procedure FormCreate(Sender: TObject);
    procedure Button1Click(Sender: TObject);
    procedure Button2Click(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form1: TForm1;

implementation

{$R *.dfm}

procedure TForm1.Button1Click(Sender: TObject);
Var s: string;
begin
  s := 'SkypeExport.exe --db "'+AddBackSlash(Edit1.Text)+ComboBox1.Text+'\main.db"';
  if ComboBox1.ItemIndex = 0 then s := s+' --timefmt 24h';
  RunDosInMemo(s,Memo1);
  Button2.Enabled := True;
end;

procedure TForm1.Button2Click(Sender: TObject);
begin
  MySysStuff.OpenFolder(AddBackSlash(ExtractFilePath(Application.ExeName))+'ExportedHistory');
end;

procedure TForm1.FormCreate(Sender: TObject);
Var s: string;
   ts: TStringList;
    t: TIntArray;
    a: Integer;
begin
  s :=  AddBackSlash(GetAppDataDirectory) + 'Skype';
  if not MyDirExists(s) then Exit;
  Edit1.Text := s;
  ts := TStringList.Create;
  MySysStuff.FindFiles(ts,s,'*.',False,False,'',False,0,False,False,True,False,t);
  for a := ts.Count-1 downto 0 do begin
    ts[a] := MyStrStuff.TrimtoLastFolder(ts[a]);
    if (ts[a] = '.') or (ts[a] = '..') or (ts[a] = 'Content') or (ts[a] = 'DataRv')
       or (ts[a] = 'My Skype Received Files') or (ts[a] = 'shared_dynco') or (ts[a] = 'shared_httpfe') then ts.Delete(a);
  end;
  ComboBox1.Items.Assign(ts);
  if ts.Count > 0 then ComboBox1.ItemIndex := 0;
  ts.Free;
end;

end.

**Comment by minamoto19** [comment]
Any news about this issue?

**Comment by Temptin** [comment]
Very sorry for the silence, I was busy and forgot about this... my email notifications on Github are off...

This is planned for the next maintenance release when I have time, so it won't be anytime soon. It's probably going to replace all illegal characters (like ":" in "live:") with a $, like "live$cooldude123.html". That way there's no need to check for existing files and add "(2)", "(3)" etc like "live_cooldude123 (2).html", because that would have brought issues of its own (on every export after the first one, it would create new files for every friend instead of properly overwriting the old ones).

Remember that Microsoft are the ones that insanely put an illegal ":" in these Skype names, so it's just fitting that we make it another illegal character that cannot be in a real Skype ID, _and_ which is legal in web URLs, i.e. the "$" symbol. Other symbols would not work: "_" = collides with valid IDs and looks like it's history with someone else. "@" = looks like an email. "#" = doesn't work if uploaded to the web (browser thinks it's a link). "+" = risks being treated as a space by browsers. So that only leaves "$" and "=" as fully legal, easily written substitute characters, and I think $ looks the cleanest of those two options.

I wish Microsoft would stop ruining Skype... ;)

**Comment by Temptin** [comment]
PS: The GUI isn't something I'd bundle with the app since it's only for Windows. I still kinda want to make a _proper_ cross-platform GUI in "Qt" for ease of use, which would be fully built into the app and would find the user's Skype folder automatically and list all contacts and let them drag a selection on the ones they want to export... but there are two problems: 1) time, which I have none anymore, 2) Qt is so big... this small <1mb application would suddenly be 50mb. :/ But Qt is the only good GUI toolkit that works on Mac, Linux and Windows... so I'm in a tough spot. If Qt was tiny, I'd have included a cross-platform GUI from day one. I don't think the value of a GUI is worth making this grow 50x in size. :/ Most people export things once and then never use it again.

**Comment by minamoto19** [comment]
Thank you.
"$" replacing ":" sounds good

**Comment by Temptin** [comment]
Good to hear. I can't promise when 1.3.1 (with the fix) will be out because I'm busy with other work and need to re-install my Windows build environment to be able to release a new version. But I will guess within a month, and I will contact you via this ticket to let you know when it's out. Sorry that I can't do it faster but I'm super busy with a major project right now.

**Comment by sthoduka** [comment]
[wxWidgets](https://www.wxwidgets.org/) is another cross-platform GUI library. I haven't used it though, so I don't know how easy it is to use, or what the size is like.

**Comment by Temptin** [comment]
Oh hey, cool to see you again Santosh! :)

I've considered wxWidgets in the past. It's a very small library (only 2 MB when statically linked), but it's suffering the same problem as the 3rd "big" cross platform library: GTK+. They're not commercially funded, so there's many bugs and problems. The wx code syntax is ugly, verbose and hard to use (very reliant on compiler macros), there's a mismash of very poor and unfunded open-source tools for building GUIs with them graphically, etc.

One of the biggest problems is that wx has a severe problem with fragmentation. There's loads of "variants" of wx for every platform. On Mac there's wxMac, xOSX/Carbon and wxOSX/Cocoa. On Linux there's lots of versions, but it seems the one to use is wxGTK (which uses GTK for rendering, I guess? seems odd...). I don't know the situation on Windows.

This fragmentation is also made worse by the fact that wx uses the platform's native GUI widgets instead of custom ones, so there's more manual work to ensure that the GUI renders bug-free on every platform. (With Qt, it uses its own renderer and you can trust it will work everywhere). That's even mentioned here: https://wiki.wxwidgets.org/WxWidgets_Compared_To_Other_Toolkits#Why_You_Shouldn.27t_Use_wxWidgets

Just going by the wxWidgets home page, it seems the leaders are wxMac for Mac, wxGTK for Linux and wxMSW for Windows. And when you've decided the "flavor" of wx to use on each platform, then you need to download those different versions and compile them manually on each platform, which slows down deployment. Although manual building of course has the huge benefit that only the functions you actually use will be linked into the executable.

Out of the top 3 (Qt, wxWidgets and GTK+), most programmers would choose Qt since it's super polished and stable. For big applications with hundreds of megabytes of textures and stuff, nobody cares about 30-50 MB of extra DLL files. But in our case Qt is too big, so it may be worth looking at wxWidgets again... It would let me write the same GUI for all platforms and only have to maintain one GUI's codebase. That'll be something to investigate _if_ I have more time for this later. ;)

Thanks for reminding me about wx, it's probably the best fit for this job actually. Another thing to investigate is statically building Qt to get the size down to about 16 MB, but that's a huuuuuge pain in the butt (~1 GB zipped source code O_O, and apparently very hard to compile) and it's still pretty large. Maybe worth it just to get the clean, stable, quality code/GUI that Qt provides though. I'll check both options later... if I have time to build a GUI at all.

**Comment by RobbieValiant** [comment]
How soon is the update for the colon issue planned? I have some stuff I can't afford to lose, but my current db file is 250 megs, large enough to send my disk usage to 100% on boot of Skype.

**Comment by Temptin** [comment]
Sorry, it's been a very long wait. I'm setting up my build environment _now_ to take care of it and another issue, and that'll be the last official update. After that people are free to fork SkypeExport, create a GUI, etc. I'm fixing this plus the recently discovered issue for people who have lots of conferences which overflows SQLite's expression tree (#11).

**Comment by Temptin** [comment]
@RobbieValiant I've finished this and the other change now. Just working on compiling the Windows version (installing Visual Studio in a VM right now...). By the time you see the message, the new version should be out on the "Releases" tab. :-)

https://github.com/Temptin/SkypeExport/releases
